### ISSUE TITLE
execute statement  "SHOW SLAVE STATUS" with java.lang.NumberFormatException: For input string: "2887547287"

### ISSUE THREAD

**Issue by holyguymjb** [jasync-sql/jasync-sql#263]
the result of  "SHOW SLAVE STATUS"

```
[root@192.168.100.24:3306 09:39:56] [(none)]>show slave status\G
*************************** 1. row ***************************
               Slave_IO_State: Waiting for master to send event
                  Master_Host: 192.168.100.25
                  Master_User: zcloud_repl
                  Master_Port: 3306
                Connect_Retry: 60
              Master_Log_File: mysql-bin.000006
          Read_Master_Log_Pos: 196
               Relay_Log_File: mysql-relay.000004
                Relay_Log_Pos: 371
        Relay_Master_Log_File: mysql-bin.000006
             Slave_IO_Running: Yes
            Slave_SQL_Running: Yes
              Replicate_Do_DB:
          Replicate_Ignore_DB:
           Replicate_Do_Table:
       Replicate_Ignore_Table:
      Replicate_Wild_Do_Table:
  Replicate_Wild_Ignore_Table:
                   Last_Errno: 0
                   Last_Error:
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 196
              Relay_Log_Space: 576
              Until_Condition: None
               Until_Log_File:
                Until_Log_Pos: 0
           Master_SSL_Allowed: No
           Master_SSL_CA_File:
           Master_SSL_CA_Path:
              Master_SSL_Cert:
            Master_SSL_Cipher:
               Master_SSL_Key:
        Seconds_Behind_Master: 0
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error:
               Last_SQL_Errno: 0
               Last_SQL_Error:
  Replicate_Ignore_Server_Ids:
             Master_Server_Id: 2887547287
                  Master_UUID: babb2933-1c19-11ec-b44e-005056aa4bbe
             Master_Info_File: mysql.slave_master_info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State: Slave has read all relay log; waiting for more updates
           Master_Retry_Count: 86400
                  Master_Bind:
      Last_IO_Error_Timestamp:
     Last_SQL_Error_Timestamp:
               Master_SSL_Crl:
           Master_SSL_Crlpath:
           Retrieved_Gtid_Set:
            Executed_Gtid_Set: 075e4821-1538-11ec-8421-005056aa9548:1-15,
388a35bf-1538-11ec-bb01-005056aa3171:1-10,
babb2933-1c19-11ec-b44e-005056aa4bbe:1-28
                Auto_Position: 1
         Replicate_Rewrite_DB:
                 Channel_Name:
           Master_TLS_Version:
       Master_public_key_path:
        Get_master_public_key: 0
            Network_Namespace:
1 row in set, 1 warning (0.01 sec)
```

The Test Code:

```
public static void main(String[] args) {
        Integer timeout = null;
        String sqlString = "SHOW SLAVE STATUS";
        Connection connection = MySQLConnectionBuilder.createConnectionPool(
                String.format("jdbc:mysql://%s:%s/%s?user=%s&password=%s","192.168.100.24",3306,"mysql","root","root123")
        );
        CompletableFuture<QueryResult> future = connection.sendQuery(sqlString);
        QueryResult queryResult;

        if (timeout == null || timeout <= 0) {
            queryResult = future.get();
        } else {
            queryResult = future.get(timeout,TimeUnit.SECONDS);
        }
       
    }
```

jasync-mysql version is 1.0.12
